name:                bot2
version:             0.1.0.0
github:              "githubuser/bot2"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions: OverloadedStrings
# DeriveGeneric

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bot2#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- aeson
- containers
- bytestring
- http-conduit
- HTTP
- random
- configurator
 

library:
  source-dirs: src

executables:
  bot2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot2

tests:
  bot2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot2
